# Generated by Django 5.0.6 on 2024-07-01 10:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='country',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='state',
            name='is_active',
        ),
        migrations.AddField(
            model_name='city',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='state',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
