# Generated by Django 5.0.6 on 2024-07-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_city_is_active_remove_country_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='is_state_available',
            new_name='is_active_available',
        ),
    ]
