# Generated by Django 5.0.6 on 2024-07-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_is_active_available_country_is_state_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
